In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
os.listdir()

['.ipynb_checkpoints', 'Churn_Modelling.csv', 'Untitled.ipynb']

In [3]:
data = pd.read_csv("Churn_Modelling.csv")

In [4]:
df = pd.DataFrame(data)

In [5]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [7]:
df.describe().T

count          mean           std          min  \
RowNumber        10000.0  5.000500e+03   2886.895680         1.00   
CustomerId       10000.0  1.569094e+07  71936.186123  15565701.00   
CreditScore      10000.0  6.505288e+02     96.653299       350.00   
Age              10000.0  3.892180e+01     10.487806        18.00   
Tenure           10000.0  5.012800e+00      2.892174         0.00   
Balance          10000.0  7.648589e+04  62397.405202         0.00   
NumOfProducts    10000.0  1.530200e+00      0.581654         1.00   
HasCrCard        10000.0  7.055000e-01      0.455840         0.00   
IsActiveMember   10000.0  5.151000e-01      0.499797         0.00   
EstimatedSalary  10000.0  1.000902e+05  57510.492818        11.58   
Exited           10000.0  2.037000e-01      0.402769         0.00   

                         25%           50%           75%          max  
RowNumber            2500.75  5.000500e+03  7.500250e+03     10000.00  
CustomerId       15628528.25  1.569074e+07  1.575323e+07  15815690.00  
CreditScore           584.00  6.520000e+02  7.180000e+02       850.00  
Age                    32.00  3.700000e+01  4.400000e+01        92.00  
Tenure                  3.00  5.000000e+00  7.000000e+00        10.00  
Balance                 0.00  9.719854e+04  1.276442e+05    250898.09  
NumOfProducts           1.00  1.000000e+00  2.000000e+00         4.00  
HasCrCard               0.00  1.000000e+00  1.000000e+00         1.00  
IsActiveMember          0.00  1.000000e+00  1.000000e+00         1.00  
EstimatedSalary     51002.11  1.001939e+05  1.493882e+05    199992.48  
Exited                  0.00  0.000000e+00  0.000000e+00         1.00

In [8]:
df.Geography.unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [9]:
X = df.iloc[:,3:13].values
y = df.iloc[:,13].values

In [10]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [11]:
#encoding categorical data
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
X_1  =LabelEncoder()
X[:,1] = X_1.fit_transform(X[:,1])
X_2 = LabelEncoder()
X[:,2] = X_2.fit_transform(X[:,2])

In [12]:
onehotencoder = OneHotEncoder(categorical_features=[1])
X=onehotencoder.fit_transform(X).toarray()

C:\Users\Afsan\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Afsan\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [13]:
X = X[:,1:]

In [14]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [15]:
#splitting
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state = 101)

In [16]:
y_test

array([0, 0, 1, ..., 0, 0, 1], dtype=int64)

In [17]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [18]:
classifier = Sequential()
classifier.add(Dense(units=6 , activation = "relu", kernel_initializer = 'uniform', input_dim = 11 ))
classifier.add(Dense(units=6 , activation = "relu", kernel_initializer = 'uniform'))
classifier.add(Dense(units=1 , activation = "sigmoid", kernel_initializer = 'uniform'))

In [19]:
classifier.compile(optimizer='adam' , metrics=['accuracy'] , loss = 'binary_crossentropy')



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [20]:
classifier.fit(X_train,
               y_train,
               epochs = 100,
               batch_size=10
               )




Epoch 1/100





7500/7500 [==============================] - 2s 312us/step - loss: 0.5965 - acc: 0.7941
Epoch 2/100
7500/7500 [==============================] - 1s 170us/step - loss: 0.5213 - acc: 0.7984
Epoch 3/100
7500/7500 [==============================] - 1s 164us/step - loss: 0.5134 - acc: 0.7984
Epoch 4/100
7500/7500 [==============================] - 1s 167us/step - loss: 0.5159 - acc: 0.7984
Epoch 5/100
7500/7500 [==============================] - 2s 201us/step - loss: 0.5004 - acc: 0.7984
Epoch 6/100
7500/7500 [==============================] - 1s 192us/step - loss: 0.4988 - acc: 0.7984
Epoch 7/100
7500/7500 [==============================] - 1s 170us/step - loss: 0.5016 - acc: 0.7984
Epoch 8/100
7500/7500 [==============================] - 1s 169us/step - loss: 0.4977 - acc: 0.7984
Epoch 9/100
7500/7500 [==============================] - 1s 168us/step - loss: 0.4992 - acc: 0.7984
Epoch 10/100
7500/7500 [==============================] - 1s 172us/step - loss: 0.4980 - acc

7500/7500 [==============================] - 1s 162us/step - loss: 0.4953 - acc: 0.7984
Epoch 65/100
7500/7500 [==============================] - 1s 165us/step - loss: 0.4952 - acc: 0.7984
Epoch 66/100
7500/7500 [==============================] - 1s 199us/step - loss: 0.4952 - acc: 0.7984
Epoch 67/100
7500/7500 [==============================] - 1s 193us/step - loss: 0.4953 - acc: 0.7984
Epoch 68/100
7500/7500 [==============================] - 1s 163us/step - loss: 0.4952 - acc: 0.7984
Epoch 69/100
7500/7500 [==============================] - 1s 166us/step - loss: 0.4953 - acc: 0.7984
Epoch 70/100
7500/7500 [==============================] - 1s 163us/step - loss: 0.4953 - acc: 0.7984
Epoch 71/100
7500/7500 [==============================] - 1s 166us/step - loss: 0.4952 - acc: 0.7984
Epoch 72/100
7500/7500 [==============================] - 1s 163us/step - loss: 0.4951 - acc: 0.7984
Epoch 73/100
7500/7500 [==============================] - 1s 165us/step - loss: 0.4953 - acc: 0.7984
Epo

In [25]:
y_pred = classifier.predict(X_test)

In [31]:
y_pred = (y_pred > 0.5)

In [32]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [33]:
from sklearn.metrics import confusion_matrix , accuracy_score
accuracy_score(y_test,y_pred)

0.79

In [39]:
confusion_matrix(y_test,y_pred)

array([[1975,    0],
       [ 525,    0]], dtype=int64)